---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: docker.io/fallenbagel/jellyseerr
      tag: 1.6.0
    env:
      TZ: America/Chicago
      LOG_LEVEL: info
    service:
      main:
        ports:
          http:
            port: &port 5055
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "requests.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      # supplementalGroups: [44, 109, 10000]
    # volumeClaimTemplates:
    #   - name: config
    #     mountPath: /app/config
    #     accessMode: ReadWriteMany
    #     size: 10Gi
    #     storageClass: local-path

    persistence:
      config:
        enabled: true
        type: nfs
        server: 192.168.1.2
        path: /tank/jellyseerr
        mountPath: /app/config

    resources:
      requests:
        memory: 500Mi
      limits:
        memory: 2000Mi
