ansible_become_pass: ENC[AES256_GCM,data:tUkxmB/RzCGuXA==,iv:e9yx1aDvBxiie45R4L3iokVBWolj/LJJrw1LvPq0EdI=,tag:oqNQh+HasPGYpBekYra5Dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNDcvOXVuaGZwb1JSek1j
            dXI0dFFmRkNiR2o4S2p3WXloUk02QzN0ekF3CnF3OU9qdW4zTk1XVE5qQ1dRRTZU
            SUNhRmU4dXVWKzdBV2YrUUZBTWI2RWcKLS0tIEdoYVZiTUtaeHprQUZEdmNMWkpW
            blVocWx5aDE2NWxSMjlvWXdWZDM0MUkKEIQ77Pcf4LvzOgxIpsJm8xeorOkX2ZvT
            EAlHcTv17ByvRQmBK3mQ7rj/NrCgIiE/ATR7TmUCQKPq7P/iBA9K/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-02T19:58:06Z"
    mac: ENC[AES256_GCM,data:536l42CCyzbpu28X5cfjzwMtdAaRd/oaIcsIJEd0+ZKJsuj+0QchAmruSV8wdM4TIRmB94uxcCxW6HEzAQm/UtYp4yaoT1Mnidn1Sax9WxvEwbsLu6yTriqEihnbkw0zXPxCmovSbfAE4goXVr9K501lu+jOUA0Bq1zVbZeQDWY=,iv:Lg118LMx53hWWPd0oRIoKdowdSEaimMVt0MExRteEpo=,tag:JoJFjzTLE8axtY17eVQxNQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
