ansible_become_pass: ENC[AES256_GCM,data:4GsfMfp06N2nlg==,iv:isli/38eFmzoQRmIiEvfSrawzIBLgqYjujewX2K4oYk=,tag:D4knFn4v6CVtEOGf+3xVRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaFNRa0Z2NHlBTWZJc2E3
            WHY4L2pHT214R0xtSGtVL2tSQUIzN2RkTUNZCkp2UEVaeUp0US9Bc3Z5RWI4QUhz
            YUI3cWNLZENudjdDcW1VSGNhYjVyLzQKLS0tIHkrNVFESEszclpCQTlSQTRONzlC
            NDE4M3QwZkJwdm1aL0RYYkpsU001Z28K71lCn8mjN9Xk2TuN9qVSo2vBlClloci0
            CpplJF3Lx15wVbk/UWIyrhnJPvKAREHAEjCODHH5aog8d7DWGfTlcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-02T20:22:32Z"
    mac: ENC[AES256_GCM,data:NvLLDfPkjiyBQs3VgIwbrWZDpClNojIT9jyF5TMPVkwW15QoHM4BR4n2IEIOg5CJeUTFDuu2Pu+hxGHnN7HEUjmsI4njxIkjitM3peIW2oPQYYsTvBhqHzFoT0sdBcjJPm7mi0nP6bE2JGxzXjI2T+7KH2GBXv1p1bwPlUyHvRc=,iv:7Ijb6YYCg6i1bG6JLQhTEr95AyTg79kvW0H06u4XBtA=,tag:9T/O460wiiWDYZ6XH4CsxA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
