---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  labels:
    disk.home.arpa/fs: zfs
    disk.home.arpa/type: hdd
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.2
  share: /tank
reclaimPolicy: Retain
volumeBindingMode: Immediate
# Note: The first two options are strictly for NFSv4.2
mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
