apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Iby6kYwFtfq2s+MQQLdBn18++LuaBh9RZxK6PDRGeoAHGmTFmebEig==,iv:T+bWtC0hpwrjL8nSwW+s/lezPyTSMkSTDKqfzmEolHQ=,tag:pvqxYpXFkayeruN4viAE7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYa1cxZDEvRzU1REg5S0pJ
            cHpaMmp2TzNLSTY1dzBIVmtQOWVCejdNY2pZCld3YXh0Z2ZUUHlKeGRSWTJMbWVo
            L096bHlINlNibnhyY3h2QjNRQmlUZ1UKLS0tIFBaYXVqdW1vdzhuNGovNGRvNy83
            YURRTjJQanQ3eFZucEFDaTU2VjhXam8K5WM0aw7OwpEEBr8dQlCuWbSt2pvIsFHy
            OXG3jEmYM43Q81pYpUsQWr6+oxJo76en0TheDfdjMv5aTxIsV+zsog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-02T20:23:30Z"
    mac: ENC[AES256_GCM,data:Mmpv2VE2AJTmFMpqXcZuRmVhw/6VuMvjA+zm9uVRnLEVsSQyaUjmL3d5tiQXK/8af2edeMMF2a1Z12AA77oc6pIV2EE4onXsUA6HiSKOG7tM/R6CnKtTJ1l78vDuvLUoJNbSMmSixuN5u2d7lm1BqkNs/ltbNr7sp3bWbEUjbzI=,iv:8guxWaytiuMsHj+IuTUwgbBUSPTph7WGUf1E1XTX808=,tag:gnD9oU7o2iAguJ8teqxy4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
