apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: security
stringData:
    onepassword-credentials.json: ENC[AES256_GCM,data:9cNtotwtJ9HdxSbuYTra26aIsMvzCCYPP71oWeDuiJMvf18WM+R47b69RrP2AVG7ee1JeIiaTM9rm0wf8Sg9EBKgJO/13b4PLFQTTMc32HHnU1+IOxBHQ5LThOhtepuCfP948FiUrGXcqP9cWvSI4upXgmG4ZyKh0AchqkZh0Hfhj1DGZr6aiIVggDnTHDtXkKmtJ6NEFp5AQKuEGsWhJIKxBhIP1Nijbg1WQrlhW5nVBCU63npDDkcWvpEwBYPUfrlkiVVe/FKDZmFzHKRW0tOFSpRe9MQL7wopq08ZLXQ1uIaSL/nUy9GYbGdhsiZvdbkQmqjgYrfQKlGOl+hsj8ZWdxWMBk/28vDzewOy7XPVd9i23n/p6HJMkcXQnnXNCpm0wopWdOkWk9Vz2GsvIIUgsDltksrdc6JXTEcqgRP/IQVqxmW9Q886056rYyUDmClikvc7kYt/YaVgzlhFe84oqfI4eZQkKm+YIQ9fUY+ACcgphaR2euAqImtO9LZupJgbtx3Ir1v/sDTvONShl+R29fjU5VzYjQyIYbTE+0QTJYItU6E3vM3dPeOql5Pn04dW2+RjicLVpd9Li6z66XZLMpnQHtZWCKYaNP+R1WFKBDMpvmU731mvDc0tp3pt8NN4plm6FoYghcP6EM0adyxeDwEPIuLSjkzqs+2Bceb0OW+HfyLgW8NbUe/UhvIqW4hBsaH9VSswmg39VjbIXrUcQneDXbRTLA01dJN1kmA1WGLoUBil1QkmAG22WzIYTDL2zMIeTuxk/nu/4e46Am7SuCa0GtPvzuEFlBcnal5OEchROVYICUCj8zrSb+CRQRzaJ+FtoLSagrXciwuNpP/g5O6TcSOun+Su03zDaLAxeIdzSD140A3jU7l0Q3HFqRoft4blJSOYTQtfcXYHLRx/5zyJI8fyjYK5d7KUmVsAi2EVL1YsU6ZO/RmEvfvAgee5CZBxO2imI++ktg61MKyDyB2jlQkDub0XmgitsIlxFwiTJ/+0RMESrI61ACP1/RZI5JrQv0agBgOE0MqJyhM8qA0DzuDqEWLLWpS2diC1fyNDA0FtCG5q4oEsOAqc57eHkYWFDx9tZe0yBYVo0WI+LapGk/JH4bESb9puccyjLsG1T8nrHSPNLQZPFayrKOaEUNdrka1AxH2Sm+R2QGLzWm7kRbPABg2RzgG/8ElrsmJXRElNyzt8/oO2dTPO3ayvxwQxi0RojJMtazVNNlj7onM+LjHH/qviO5s15BBhW7B1ivQKo+nevpBNIy9D+ZlYIa2TQSadu0i3VrPAay7/VRddncMnAm6cz79wd8VPh3aDYKlFs5VRgZQtSA73QMycLlYU2qBZeJB2/QzxoxHQn3sqP7vcgjwbt6XXR0Ut5C7VmiU1Nn2wzC8FERh2On6slkPqMb84jr/nCaRlnKpTXi01w0g96y5M48RQmmlIqPsnSXD0ujDTu+KO9zbExFZih+Y8iuKHPKiIpq2hI2FmQxI472e27ZLgo2kcARo6mfWPxr/TDIRWClb/NtkdpF+MWy+1XJU1FjpFoq9S6/LrwVSHEAKaLVLzoj01cmgJ2dah7VON2Sd4BbDX2zgZ9OmHn0hdoJNjNMyOY3hiR/VwGUsd3Izn/9sfp83aAmSSEPQSqiJUyO64CoZHTiVlmstGUtK+ARuocRZD0XuDHJ1f2xKuL4BFtiawziZKSYCc5ZBKHtX5Us71tJsb1oy/nMa1j8CoqTDBNyt59nfQLkcazGiscH+QIfTMzRUyD/xLG66fI+KInSr9xhbJQU/EQfd2wcR0fOH7wpZBJGUxqnBUPINk9Yi1WUeVWEfGjpAzMQGOUog1WMxmMWhRzGXIaSm0dSrj4IJ+2qFmMw3tbkukL/n3QJNv1J14PkI2X6l/Zn1ZprEnNFYRFVruy22AM4WGARxUj2hbjWlP,iv:F6/XDQXML1NYXIOMv3Q7HNGLvG6J1EhJEe5nRLIeiq0=,tag:lsnYZkJYiXwcEUgbtWrkSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSlQrZnk0aWIxeThKZlpK
            TzFuZGZnL2V6Q3l2SCtXQWpjMnh6RUhpZjNBClZ1SEIxbGE3akZsVDNuTUhqWVJk
            WTVJdkVrK1hBSlpLUVRRRGJUelhHS1kKLS0tIDZmVkZzMkFDdEkzanNRTTJxNlI1
            K0gyODBhZ1U0bzdLWUN5SGsvVHlZdncKajAmkjyBfuV18RpQ5KYL83AtWCeoBJj/
            y8lNzOEvFsRcY5c3UrWr3TF96zubKy989ATJd3FHn7yn12WwExui5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T19:56:40Z"
    mac: ENC[AES256_GCM,data:jImX1hSgXFDXhwuaU3hrHz3ny277vrx0mC/2PmKcTfg/fnoDizGKmoellEglrjoTjdLRXJtUP+niAf0pWmGgPNz/4JnDT6i4ku6o5HMQ089kZ/AQu9v1aQUeee28NMqZTXmdLajN3KXRJfHKLPcfqQER1u6jvpknpdLdSLXI16Q=,iv:xXfe8hx6K0OeSmIkOoAGlgJGr/J0fMBvH84VCAWN9/0=,tag:Jo+fwsvD09e5ww9xwQiCRw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: security
stringData:
    token: ENC[AES256_GCM,data:2+CYmVe/aXTOtYbzjUEmLy9c4pWUEnQGuVpb+JMAakwFjIRVzlT+EMoRqerpsHR2P0EvHhbUkRqy/rdB0421nIC0pT9kNt1Pu7O4yoZY1JIz8xzFvbPNxlJgq/q3LjOADOZG22pn2iIsi2zEmloNhGI5z1TEXPARbtbBV3qi+cvzlwvGQU3Oz02bb656AEQWL/vrawUU+e2T144sa3dvkCBtmvP3QIRsjjilHjg4LDjVCVoPxCFX+DfFxQHQu3RR1GFU4XMnXDsdgv5obIX/Kss0yM5/zVMA6Vmq6uXVzeuikmisaY3P2pO3orQBuByoNMcR0pQE20mtsxVWuOVYQsvcNbLLd9+9etPBEe3lSZ34fKsUF7WCwdfUsYu38d/Kk+LFS6EvN+ZVyPVo+eS5LrbpE4duV6r4rx6IzZY4BToNvWozLskOLqcdjU1HjBXawjW/r1XGo8s1OI75FB3AXe5wMXKXHC+7n844JK28yYPePmw73QfxnyHujT28yycKaieE+aacQEjKX+OyOMQFlaxIKGTapA2tQ5qoGMtLG/I14xgvV1YxF0j+2Ntb11g5WbDwfC8ChOk8oI1VbD8OJKZUL0ems4+mixxwNnY7TKo1m8m9xj2tS99pQxpeWPr5RcMn+IbDSKpowy0PofJqm+W1kiqVgh5YvecxLsaHPin2a1YBZjovUZ9vQUPXSdoZ2e6YZ31v3Uo7Pf7s3RTYkXUERQwXDKPoV+vXxwX2WnH1PKPvvuwUWVpPllTFH8o+FxRwBPzuIfeW0ManLKc5tPjIVtbWrmpvoEI8C9sABqqiB6d7d56Br5oJWXRCWroYJHCmKzZTUoebFh19rhbksIsD,iv:48NqfioPHEGo6o5eJtILcDDhhy73HlmOTm201OM7DEc=,tag:69mB9GHwUbPq/nnSHy8W6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSlQrZnk0aWIxeThKZlpK
            TzFuZGZnL2V6Q3l2SCtXQWpjMnh6RUhpZjNBClZ1SEIxbGE3akZsVDNuTUhqWVJk
            WTVJdkVrK1hBSlpLUVRRRGJUelhHS1kKLS0tIDZmVkZzMkFDdEkzanNRTTJxNlI1
            K0gyODBhZ1U0bzdLWUN5SGsvVHlZdncKajAmkjyBfuV18RpQ5KYL83AtWCeoBJj/
            y8lNzOEvFsRcY5c3UrWr3TF96zubKy989ATJd3FHn7yn12WwExui5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T19:56:40Z"
    mac: ENC[AES256_GCM,data:jImX1hSgXFDXhwuaU3hrHz3ny277vrx0mC/2PmKcTfg/fnoDizGKmoellEglrjoTjdLRXJtUP+niAf0pWmGgPNz/4JnDT6i4ku6o5HMQ089kZ/AQu9v1aQUeee28NMqZTXmdLajN3KXRJfHKLPcfqQER1u6jvpknpdLdSLXI16Q=,iv:xXfe8hx6K0OeSmIkOoAGlgJGr/J0fMBvH84VCAWN9/0=,tag:Jo+fwsvD09e5ww9xwQiCRw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
