apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:oNR/BKQOfvGblLJsqaquBUpGzexaR5SpxkrJv/YZ5EXF1zvuinVqPQ==,iv:tBAL+IEI2wk8gB4+J4MLXl4PQM5If0Oh+SOMVuxM998=,tag:le78Z4pSrHLDFAUC17tsrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWko5VlRQaFQ5eU5rRFNC
            bkpzOHRhZFMxL24ycVdrb1hUOFhPU01ZV24wClFmcXVkK3IvTUpSMEwrQmJDaFh0
            b2dMMmZCTk1tTGZrQzZ5VEJKU2tESEUKLS0tIDhNRmliSXJ6MU1FTlZQOEJGSzdU
            Q3JWN2VvN2RPOUE4KzdWdCs1c2VJOTQKZRH8QSrJzQZ5VE9Zwtr4MQUxt7ZZwMbG
            CymicpgRM9sKd6Ag4cUnTfE6aa6aFeZ5160F6uGkF39ggabbUscJnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-02T19:59:04Z"
    mac: ENC[AES256_GCM,data:CYjXL9DZgHep1IuzWATXBSSLl/JrhPOjC0R6m5Wbv5vnZFN6tBw4urepa+HBtlLt29gUPQzddA4gij62nompwoYgBJQiyimjRqNLYssOLiFNfCnfZ+i4akVZfv8/cRQyD74vTnZi0lKC1ZoYiShRvLkHkQ7y4rVS69W3tc2IyYg=,iv:phFEvOhhGZ9NLEMZhy3NF33cqdOghdKnd55qD0tMu5M=,tag:PTAucuppTljJtbGfyMzhUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
