---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: default
data:
  DB_PORT: "5432"
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.media.svc.cluster.local:3003
  IMMICH_SERVER_URL: http://immich-server.media.svc.cluster.local:3001
  IMMICH_WEB_URL: http://immich-web.media.svc.cluster.local:3000
  LOG_LEVEL: verbose
  REDIS_URL: ioredis://eyJkYiI6MTUsInNlbnRpbmVscyI6W3siaG9zdCI6InJlZGlzLW5vZGUtMC5yZWRpcy1oZWFkbGVzcy5kYi5zdmMuY2x1c3Rlci5sb2NhbCIsInBvcnQiOjI2Mzc5fSx7Imhvc3QiOiJyZWRpcy1ub2RlLTEucmVkaXMtaGVhZGxlc3MuZGIuc3ZjLmNsdXN0ZXIubG9jYWwiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtbm9kZS0yLnJlZGlzLWhlYWRsZXNzLmRiLnN2Yy5jbHVzdGVyLmxvY2FsIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6InJlZGlzLW1hc3RlciJ9Cg==
  TRANSFORMERS_CACHE: /usr/src/app/.transformers_cache
  TYPESENSE_DATA_DIR: /config
  TYPESENSE_HOST: immich-typesense.media.svc.cluster.local
