---
session:
  name: authelia_session
  domain: phekno.io
  cookies:
    - domain: phekno.io
      authelia_url: 'https://auth.phekno.io'
      name: authelia_session
      same_site: lax
      inactivity: 5m
      expiration: 1h
      remember_me: 1d
  redis:
    host: redis.db.svc.cluster.local
    database_index: 14
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.db.svc.cluster.local
          port: 26379
        - host: redis-node-1.redis-headless.db.svc.cluster.local
          port: 26379
        - host: redis-node-2.redis-headless.db.svc.cluster.local
          port: 26379

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules:
    - domain: ["jellyfin.phekno.io"]
      resources: ["^/metrics.*$"]
      policy: deny
    - domain: ["invite.phekno.io"]
      resources: ["^/join(/.*)?$", "^/j(/.*)?$", "^/setup(/.*)?$", "^/static(/.*)?$"]
      policy: bypass

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        secret: "${GRAFANA_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://grafana.phekno.io/login/generic_oauth"]
      - id: immich
        description: Immich
        secret: "${IMMICH_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "email"]
        redirect_uris: ["https://photos.phekno.io/auth/login", "app.immich:/"]
