# https://external-secrets.io/v0.8.1/provider/1password-automation/
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    # This is basically what you're going to "name" the secret to k8s...
    # Like...this is how k8s will refer to the secret or something
    name: sabnzbd-secret
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        # Name of "password" in 1Password, in this case it's "sabnzbd"
        key: sabnzbd
        # Value we want that's stored in the "password"
        # In this case, we have a field named "api_key"
        property: api_key
    - secretKey: nzb_key
      remoteRef:
        key: sabnzbd
        property: nzb_key
