---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 4.1.0@sha256:d7eabae44168417a6acbc8f6e8510b0187a3f26d648941b3cf61b4c04a904da2

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    env:
      SABNZBD__PORT: &port 8080
      SABNZBD__HOST_WHITELIST_ENTRIES: >-
        sabnzbd,
        sabnzbd.downloads,
        sabnzbd.downloads.svc,
        sabnzbd.downloads.svc.cluster,
        sabnzbd.downloads.svc.cluster.local,
        sabnzbd.phekno.io
      SABNZBD__API_KEY:
        valueFrom:
          secretKeyRef:
            name: sabnzbd-secret
            key: api_key
      SABNZBD__NZB_KEY:
        valueFrom:
          secretKeyRef:
            name: sabnzbd-secret
            key: nzb_key

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host "sabnzbd.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      incomplete:
        enabled: true
        type: emptyDir
      media:
        enabled: true
        type: nfs
        server: 192.168.1.2
        path: /tank/video
        mountPath: /media
      # downloads:
      #   enabled: true
      #   type: nfs
      #   server: 192.168.1.2
      #   path: /tank/nzbget_downloads
      #   mountPath: /config/Downloads

    resources:
      requests:
        cpu: 15m
        memory: 4000Mi
      limits:
        memory: 8000Mi

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: local-path
      - name: downloads
        mountPath: /config/Downloads
        accessMode: ReadWriteOnce
        size: 500Gi
        storageClass: local-path
