---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: expanse-kopia
  namespace: monitoring
spec:
  staticConfigs:
    - targets: ["expanse.turbo.ac:51516"]
  metricsPath: /metrics
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: expanse-minio
  namespace: monitoring
spec:
  staticConfigs:
    - targets: ["expanse.turbo.ac:9000"]
  metricsPath: /minio/v2/metrics/cluster
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: expanse-smartctl-exporter
  namespace: monitoring
spec:
  staticConfigs:
    - targets: ["expanse.turbo.ac:9633"]
  metricsPath: /metrics
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: expanse-zrepl
  namespace: monitoring
spec:
  staticConfigs:
    - targets: ["expanse.turbo.ac:9811"]
  metricsPath: /metrics
