---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: expanse-node
  namespace: monitoring
spec:
  staticConfigs:
    - targets: ["10.100.50.5:9100"]
  metricsPath: /metrics
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: smartctl-exporter
  namespace: monitoring
spec:
  staticConfigs:
    - targets: ["10.100.50.5:9633"]
  metricsPath: /metrics
