---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: pikvm
  namespace: monitoring
spec:
  staticConfigs:
    - targets: ["pikvm.turbo.ac"]
  metricsPath: /api/export/prometheus/metrics
