---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: zigbee-controller
  namespace: monitoring
spec:
  staticConfigs:
    - targets: ["zigbee-controller.turbo.ac"]
  metricsPath: /metrics
