apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:AJ8nI7lSZfEaHNwa,iv:eqJ0ugEou/TGifPJV5zn/kdEpdlm2UOwnjMiOVuZTPU=,tag:bB4FE7L/ZvuJ5dmRL/RR6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSW0rcjczS2hqVnFTSGxh
            dC81bkRsRlNacUNuaUVaNEhmaHJvRzMvakFnCklXYWNtVmoyQk5BSkxaUTNuUVdM
            M3pFWXJmZ2JzSVVDUWRGSXJmZy9FTlUKLS0tIGxzSDhzVnBpbHZRT0JLTkU2MTN2
            amdoQmJXbU9FZUg5Lzh3N0lvQ0VYdTQKbaddeS7/HNR/yPnoFr7uiJwJEHuhAUgx
            RkHDy1KKqs9n+f4cv3MOyX1yyF6dSWJThDmhYPUyDsXWvaBZJ83P+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T21:46:31Z"
    mac: ENC[AES256_GCM,data:PsgUfHbtYz1AdHEmQbFcvjhJVDpnIGEtCjjGIUBXNxfzIQqEAheVtVeFbb3Pu0hhWyv4WUa1FNaEe78Sdq6GyzGcnQv+rayVqOy8cBhqJpdKCV8xjKWWW57q0M1NFhHEBfoTAuNf2xKn4gO/Dc0WjP1RiqlVsG8elm/zLtML6PA=,iv:CZ6ROtxYLveYxgGGcXuUGtAt2CBn7cdhPgCw39Nc5zw=,tag:LOtLZ1aEvkCBsuTTbOvlZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
