apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:/gBhunD74/lInOZ8,iv:nnI1+hQg0nYUzwNCkRVElGmTuSy1ju7jg8YvSgiPJRQ=,tag:DI7yBgPafjTF8+IWPGRkAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ0RvaDVVMWkrVXlXWHFh
            UkJSQXVVaXkwSStCS1ZmRmZkZEpEMUdFK2c0Cjd4WXM3VkxFMVZ3bTNKaEd3Wlox
            ayt2UXlpSjl0WDNlbjhoekJpZk91M2cKLS0tIEVSYnZiV3BMb1FvRjBaWXZ0SzZx
            eGtCVTFSZlJaN3FNS3B4SnVqd3ZzcjgK8JuYZfzmdAS1bXKHexsRNIX5W9ZbyjDR
            ru0pHqdClX4EykfLno7ojQd/o6hQwv8EJIyPwxjznyalwJMZQWf0gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-02T19:59:02Z"
    mac: ENC[AES256_GCM,data:iFrRZZeKRpg5qbc3DkGSvITY7SDbY4OF9Fni5gHUIIh5Etsd6G2X6JXhrm5g+6lxknedWyH0pRVb83vXot4tdI/FEnfrvxdNgSkxRPk4ety2nwq8UUDbp01dg7j+fgKYT2hWRbqVxR8wevG1hy/FUY8kofc8KZcdentPprJlD3o=,iv:jwtGYqGYzHdFPU9kRXyK+Pckt6xilF078Y4N00jRkFY=,tag:/4YTltV4IeZyApV8LWqPsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
