---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: db
  annotations:
    coredns.io/hostname: postgres.phekno.io
    io.cilium/lb-ipam-ips: 10.100.50.103
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    role: primary
