apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ixBRjYDzvQ9rHSgtEnn/Ig+ZygjrE4UI+X5LCPcianTjrbrc,iv:4ehoBtLYo0xdOiaDub2UjWElgpb+cjdCIWSH/Fgi+rA=,tag:IWZRhm86a4JWYdjfFK10aA==,type:str]
    credentials.json: ENC[AES256_GCM,data:vQWi+5g0CDJedwJ27P1BlY/yrz2NfY2eGQK2TBFgP1UZE20k0yvwWD1CkREdOYo2UbhAXuqCkwOjX8BwDX2k1MWZGXHAZLbKpcS8ad4GAhfbEZ44/embGqZEq3wZWXQSq/9S3vc7alxr1bib4AqHJSZ2b5YV7QWaLXLu4OEkc/I5RvNktUUEp6voogghalTjxALQ5Kw5Vr2HDGXGMzFPky6zH/ubU8cUtOgkIlWneA==,iv:M2H1Fs7bE9sK/iaZVH237p6l82O6gR8MxX8QLLb+2vs=,tag:SeBCCAGNpLPSHQhkPhKWFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbEtranlsNmhqVzJSUWlE
            NDV0U3MvSUFkcndkWGUzamVma3RKa09KZzBzCm1XMXpGeGhRU2JETWcxelkxNUli
            YTdoQkVWZUFJUHE2YWJESTYrdW9jOXMKLS0tIHFYakorWDV0Z04vY3RYSWtjTDNr
            aEZpYWdsVjdBcWNuTFZQbmpRaVV3S0kKpY4ZIhdF26pNySNhGIbLzQ1O8lF5GhPH
            nv3yLSTNcSh8L5Olrcq9G+xgQEOW1TuxndFYCRs0/J5Zmg4X24pqUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-02T20:23:31Z"
    mac: ENC[AES256_GCM,data:Xs7+Iiqg6NXQSqDUL3y3JTB7j5ZI2ZcDlMuedqOz5z+S9GQCKVzW4WiHYHhIoqywfVFAhQ4sUCYpLzBCRRY63R/qCQA5DkpcmuZxowFWQc3m8D9imUwBWcqqnYPQjUNyNbgFdJH69byhpZKAPDgGCDr+TptOERE1eAY2n9Z48Sk=,iv:uGJvdqkL5UTHgvJBd/kaQzQojrIGCZnXhoSeAG/0T5g=,tag:IGdMhhGpYsXfwD35rJq/0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
