apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:D7OKvIoSNpVGFnW/fHJOOM9nQEpUzOmmAhyc+2YxXa798mif,iv:fo6Uhc3pn9jKd2ufMaWwZmGnUkI8H1nSjAPc9hnUas0=,tag:3Iz4cD7BXioRAEEAmauSSg==,type:str]
    credentials.json: ENC[AES256_GCM,data:3eMTMuPp+ggjcCop/HKDcVwNdFKSwG4dJPg47RpYmP9OZkNNYzIK2HzhEP/tm9VUkS5TSXLpBpBtrF6DlAyvAIgi2SonR3jFlimoafFXVYUqrRCPul26bezBG/ZD6w2w40PyABCdvpC8pRB23Ok7LyNpyDo+B2MEcCeAWEItMF2qsz5RxcYsOGE23nUovTub5wDiOrcIs+1VLOHCFw363RrN67ILX6iN/DKFDS5ekw==,iv:KOynqgJkQZx/6nOpiE1M3uhYp7JB/aTtrd6dxv3w0Rs=,tag:Sj8vR7tEux0R9JAoIolN+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0c2xWQ2N3MXE5K0EzbCtO
            TnlBOUJMQ2VFam5rM2pBTzBnTU1DTHJiWVRvClNxazlPeGFyR2FTMGQ5Zys4bWxy
            MmtQZWYrUFpNbkdCKzlaT011UVFNSzgKLS0tIHlRbXQ0TUNlNWdnUjB4bGR2U1ly
            Nk9MZGpYMVBVTTB1Unc3VVhGOTNsZWMKnc1djFtqEigDwBVij5HayKOvKquyj4to
            1pxmbxqoIzENUXIZcIiFNMf5EeNo+EsqMLWN9B4FOXMCxVWrZAiaNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-02T19:59:03Z"
    mac: ENC[AES256_GCM,data:TlVTpngatj3bGdC+n6nLnIbEjkH1TphKf9buTpqNdSLFWEq2f6yvc+hsWzgjW8WGSFA61/49SejdvOPMoJ/gpeqJnzgOk1qJItYoRQ5F8STGJERbjV9GeFEm1NI0Mr4VDbyWkKB7eRlT6Kq9xfqWKnVhZufLINDGL4rKUpyM2qE=,iv:C7TRN3kh5a4y/ukaMKOVgnfMi6jE6GJl9Yn02asoNcY=,tag:WB0RPqRSYPHEE7zFKNcujw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
