---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-secret
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lldap-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        LLDAP_JWT_SECRET: "{{ .LLDAP_JWT_SECRET }}"
        LLDAP_LDAP_USER_PASS: "{{ .LLDAP_LDAP_USER_PASS }}"
        LLDAP_USER_DN: "{{ .LLDAP_USER_DN }}"
        LLDAP_LDAP_USER_EMAIL: "{{ .LLDAP_LDAP_USER_EMAIL }}"
        LLDAP_SERVER_KEY_SEED: "{{ .LLDAP_KEY_SEED }}"
        LLDAP_DATABASE_URL: postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-rw.db.svc.cluster.local/lldap
        # LLDAP SMTP options
        LLDAP_SMTP_OPTIONS__SERVER: "{{ .SMTP_HOST }}"
        LLDAP_SMTP_OPTIONS__PORT: "{{ .SMTP_PORT }}"
        LLDAP_SMTP_OPTIONS__USER: "{{ .SMTP_USERNAME }}"
        LLDAP_SMTP_OPTIONS__PASSWORD: "{{ .SMTP_PASSWORD }}"
        LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: "STARTTLS"
        LLDAP_SMTP_OPTIONS__FROM: "LLDAP Admin <lldap_admin@phekno.io>"
        LLDAP_SMTP_OPTIONS__REPLY_TO: "Do not reply <noreply@phekno.io>"
        LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: "true"
        # Postgres Init
        INIT_POSTGRES_DBNAME: lldap
        INIT_POSTGRES_HOST: postgres-rw.db.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: lldap
    - extract:
        key: cloudnative-pg
    - extract:
        key: smtp
