---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin
  namespace: db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pgadmin-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PGADMIN_DEFAULT_EMAIL: "{{ .username }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .POSTGRES_SUPER_PASS }}"
        PGADMIN_CONFIG_ENABLE_PSQL: "True"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: pgadmin