---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db
resources:
  - ./externalsecret.yaml
  # - ./gatus.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
  # - ./volsync.yaml
configMapGenerator:
  - name: servers-json
    files:
      - config/servers.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled