---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-config
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
