---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authelia
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-lldap
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-authelia-redis
  path: ./kubernetes/apps/security/authelia/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: authelia
      namespace: security
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authelia-redis
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/security/authelia/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ubernetes
  wait: false # no flux ks dependents